const express = require('express');
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'aseada_secret_2024';
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => res.json({ mensaje: 'Aseada API funcionando', version: '2.0.0', db: 'PostgreSQL' }));
app.listen(PORT, '0.0.0.0', () => console.log('Aseada PostgreSQL corriendo en puerto ' + PORT));
